### ISSUE TITLE
Downloaded template does not run

### ISSUE THREAD

**Issue by JohnDoweII** [nuxt-ui-pro/dashboard#68]
I've downloaded the `.zip` file from this repository, installed dependencies and tried to run the project, 
but the same error appears each time:
`----`
`|ERROR| [nitro] [unhandledRejection] Cannot read properties of undefined (reading 'wrapper')`
`----`
more details here:
```js
 at _sfc_ssrRender (node_modules\.pnpm\@nuxt+ui-pro@1.4.4_magicast@0.3.5_rollup@4.24.0_vite@5.4.9_@types+node@22.7.7_terser@5.36.0___c4kb5od7s7vmtafn5kgnekapwa\node_modules\@nuxt\ui-pro\components\main\Main.vue:41:22)
  at renderComponentSubTree (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:715:9)
  at renderComponentVNode (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:664:12)
  at Module.ssrRenderComponent (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
  at _sfc_ssrRender (app\error.vue:66:31)
  at renderComponentSubTree (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:715:9)
  at renderComponentVNode (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:664:12)
  at Module.ssrRenderComponent (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
  at default (node_modules\.pnpm\nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.7_eslint@9.13.0_jiti@2.3.3__ioredis@5.4.1__iadbvypbtliyn543dneg2m6caa\node_modules\nuxt\dist\app\components\nuxt-root.vue:96:38)
  at Module.ssrRenderSuspense (node_modules\.pnpm\@vue+server-renderer@3.5.12_vue@3.5.12_typescript@5.6.3_\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:485:5)
  ```
  
I've used pnpm, and npm both on fresh, unziped directories. 
Logs prior to error:
```js
Lockfile is up to date, resolution step is skipped
Packages: +1084
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1084, reused 1084, downloaded 0, added 1084, done

dependencies:
+ @iconify-json/heroicons 1.2.1
+ @iconify-json/simple-icons 1.2.9
+ @nuxt/fonts 0.10.0
+ @nuxt/ui-pro 1.4.4
+ @unovis/ts 1.4.4
+ @unovis/vue 1.4.4
+ @vueuse/nuxt 11.1.0
+ date-fns 4.1.0
+ nuxt 3.13.2
+ v-calendar 3.1.2

devDependencies:
+ @nuxt/eslint 0.6.0
+ eslint 9.13.0
+ vue-tsc 2.1.6

> nuxt-ui-pro-template-dashboard@ postinstall [...]\dashboard-main\dashboard-main
> nuxt prepare

ℹ Using default Tailwind CSS file
ℹ Nuxt Icon server bundle mode is set to local 
✔ Nuxt Icon discovered local-installed 3 collections: heroicons, simple-icons, vscode-icons 
ℹ Running with compatibility version 4 
✔ Types generated in .nuxt 

Done in 32.6s



> pnpm run dev

> nuxt-ui-pro-template-dashboard@ dev C:\Users\Gishi\Downloads\dashboard-main (1)\dashboard-main
> nuxt dev

Nuxt 3.13.2 with Nitro 2.9.7        
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                             
  ➜ DevTools: press Shift + Alt + D in the browser (v1.6.0)                                                                                                   
ℹ Nuxt Icon server bundle mode is set to local 
✔ Nuxt Icon discovered local-installed 3 collections: heroicons, simple-icons, vscode-icons 
ℹ Running with compatibility version 4  
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/    
✔ Vite client built in 70ms 
✔ Vite server built in 110ms 
✔ Nuxt Nitro server built in 1172 ms
ℹ Vite server warmed up in 7216ms  
ℹ Vite client warmed up in 8436ms
```

**Comment by benjamincanac** [comment]
Would you mind trying with latest version?

**Comment by ilrein** [comment]
@benjamincanac I just tried to run the project from today, and noticed similar errors:

```ERROR  Cannot read properties of undefined (reading 'theme')                                               nuxt 12:45:44 p.m.

    at a (node_modules/@nuxt/ui-pro/dist/shared/ui-pro.CqnQuCPp.mjs:1195:241)```

**Comment by benjamincanac** [comment]
Do you encounter same errors using the CLI? `npx nuxi init -t github:nuxt-ui-pro/dashboard`

**Comment by ilrein** [comment]
Yes, with using the CLI. Full output below:

➜  contract-work npx nuxi init -t github:nuxt-ui-pro/dashboard
Need to install the following packages:
nuxi@3.23.1
Ok to proceed? (y) y


        .d$b.
       i$$A$$L  .d$b
     .$$F` `$$L.$$A$$.
    j$$'    `4$$:` `$$.
   j$$'     .4$:    `$$.
  j$$`     .$$:      `4$L
 :$$:____.d$$:  _____.:$$:
 `4$$$$$$$$P` .i$$$$$$$$P`

ℹ Welcome to Nuxt!                                                                             nuxi  12:50:27 p.m.

✔ Where would you like to create your project?
dashboard
ℹ Creating a new project in dashboard.                                                         nuxi  12:50:31 p.m.

✔ Which package manager would you like to use?
bun
◐ Installing dependencies...                                                                    nuxi  12:50:33 p.m.
bun install v1.2.5 (013fdddc)

$ nuxt prepare
ℹ Nuxt Icon server bundle mode is set to local                                                                                12:50:40 p.m.
✔ Nuxt Icon discovered local-installed 2 collections: lucide, simple-icons                                                    12:50:40 p.m.
ℹ Running with compatibility version 4                                                                                   nuxt 12:50:40 p.m.
✔ Types generated in .nuxt                                                                                              nuxi  12:50:40 p.m.

+ @nuxt/eslint@1.2.0
+ eslint@9.22.0
+ typescript@5.8.2
+ vue-tsc@2.2.2
+ @iconify-json/lucide@1.2.31
+ @iconify-json/simple-icons@1.2.29
+ @nuxt/ui-pro@3.0.0
+ @unovis/ts@1.5.1
+ @unovis/vue@1.5.1
+ @vueuse/nuxt@13.0.0
+ date-fns@4.1.0
+ nuxt@3.16.0
+ zod@3.24.2

1006 packages installed [7.08s]

Blocked 2 postinstalls. Run `bun pm untrusted` for details.
✔ Installation completed.                                                                                               nuxi  12:50:40 p.m.

✔ Initialize git repository?
No

✔ Would you like to install any of the official modules?
@nuxt/content – The file-based CMS with support for Markdown, YAML, JSON, @nuxt/eslint – Project-aware, easy-to-use, extensible and future-proof ESLint
integration, @nuxt/fonts – Add custom web fonts with performance in mind, @nuxt/icon – Icon module for Nuxt with 200,000+ ready to use icons from Iconify,
@nuxt/image – Add images with progressive processing, lazy-loading, resizing and providers support, @nuxt/scripts – Add 3rd-party scripts without sacrificing
performance, @nuxt/test-utils – Test utilities for Nuxt, @nuxt/ui – The Intuitive UI Library powered by Reka UI and Tailwind CSS
[ nuxi  12:50:49 p.m.] ℹ Resolved @nuxt/content, @nuxt/eslint, @nuxt/fonts, @nuxt/icon, @nuxt/image, @nuxt/scripts, @nuxt/test-utils, @nuxt/ui, adding modules...
ℹ @nuxt/eslint is already installed                                                                                                     nuxi  12:50:49 p.m.
[ nuxi  12:50:49 p.m.] ℹ Installing @nuxt/content@3.3.0, @nuxt/fonts@0.11.0, @nuxt/icon@1.11.0, @nuxt/image@1.10.0, @nuxt/scripts@0.11.2, @nuxt/test-utils@3.17.2, @nuxt/ui@3.0.0 as dependencies
 WARN  Moving eslint that was installed by a different package manager to "node_modules/.ignored"
 WARN  Moving @nuxt/eslint that was installed by a different package manager to "node_modules/.ignored"
 WARN  Moving typescript that was installed by a different package manager to "node_modules/.ignored"
 WARN  Moving vue-tsc that was installed by a different package manager to "node_modules/.ignored"
 WARN  Moving @iconify-json/lucide that was installed by a different package manager to "node_modules/.ignored"
 WARN  8 other warnings
Packages: +1237
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1324, reused 1242, downloaded 0, added 1237, done

dependencies:
+ @iconify-json/lucide 1.2.29
+ @iconify-json/simple-icons 1.2.28
+ @nuxt/content 3.3.0
+ @nuxt/fonts 0.11.0
+ @nuxt/icon 1.11.0
+ @nuxt/image 1.10.0
+ @nuxt/scripts 0.11.2
+ @nuxt/test-utils 3.17.2
+ @nuxt/ui 3.0.0
+ @nuxt/ui-pro 3.0.0
+ @unovis/ts 1.5.1
+ @unovis/vue 1.5.1
+ @vueuse/nuxt 13.0.0
+ date-fns 4.1.0
+ nuxt 3.16.0
+ zod 3.24.2

devDependencies:
+ @nuxt/eslint 1.2.0 already in devDependencies, was not moved to dependencies.
+ eslint 9.22.0 already in devDependencies, was not moved to dependencies.
+ typescript 5.8.2 already in devDependencies, was not moved to dependencies.
+ vue-tsc 2.2.2 already in devDependencies, was not moved to dependencies.

╭ Warning ───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                    │
│   Ignored build scripts: @parcel/watcher, better-sqlite3, esbuild, maplibre-gl, sharp, vue-demi.   │
│   Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.           │
│                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯

Done in 8.5s using pnpm v10.6.2
Already up to date
Progress: resolved 1324, reused 1242, downloaded 0, added 0, done

dependencies:
+ @unhead/vue 2.0.0-rc.10 (2.0.0-rc.13 is available)

Done in 1s using pnpm v10.6.2
ℹ Adding @nuxt/content to the modules                                                                                                   nuxi  12:50:59 p.m.
ℹ @nuxt/eslint is already in the modules                                                                                                nuxi  12:50:59 p.m.
ℹ Adding @nuxt/fonts to the modules                                                                                                     nuxi  12:50:59 p.m.
ℹ Adding @nuxt/icon to the modules                                                                                                      nuxi  12:50:59 p.m.
ℹ Adding @nuxt/image to the modules                                                                                                     nuxi  12:50:59 p.m.
ℹ Adding @nuxt/scripts to the modules                                                                                                   nuxi  12:50:59 p.m.
ℹ Adding @nuxt/test-utils to the modules                                                                                                nuxi  12:50:59 p.m.
ℹ Adding @nuxt/ui to the modules                                                                                                        nuxi  12:50:59 p.m.

[@nuxt/content 12:51:00 p.m.]  WARN  No content configuration found, falling back to default collection. In order to have full control over your collections, create the config file in project root. See: https://content.nuxt.com/docs/getting-started/installation

ℹ Nuxt Icon server bundle mode is set to local                                                                                                12:51:01 p.m.
ℹ Running with compatibility version 4                                                                                                   nuxt 12:51:01 p.m.

 ERROR  Could not compile template ui-pro/prose/a.ts.                                                                                     nuxt 12:51:01 p.m.


 ERROR  Cannot read properties of undefined (reading 'theme')                                                                             nuxt 12:51:01 p.m.

    at a (dashboard/node_modules/.pnpm/@nuxt+ui-pro@3.0.0_@babel+parser@7.26.9_change-


 --- Here are a ton of errors, I removed them, they are all related to missing `theme`--- 

✔ Types generated in dashboard/.nuxt                                                                                                    nuxi  12:51:01 p.m.
                                                                                                                                         nuxi  12:51:01 p.m.
✨ Nuxt project has been created with the nuxt-ui-pro-dashboard template. Next steps:
 › cd dashboard                                                                                                                          nuxi  12:51:01 p.m.
 › Start development server with bun run dev                                                                                             nuxi  12:51:01 p.m.
➜  contract-work

**Comment by ilrein** [comment]
I noticed there is a different output when using `pnpm` instead, but that crashes on a `better_sqlite` error instead.

**Comment by Rednas83** [comment]
Trick is not to select **@nuxt/ui** when calling `npx nuxi@latest init -t github:nuxt-ui-pro/dashboard`
![Image](https://github.com/user-attachments/assets/ce268517-b9db-4094-bc89-827e0c616b35)
With **pnpm** it's also important to downgrade to v9 when using `@nuxt/content` to avoid the binding error with `better_sqlite`
`"packageManager": "pnpm@9.15.9"`

**Comment by mrwwalmsley** [comment]
I also had challenges with: 

`npx nuxi@latest init -t github:nuxt-ui-pro/dashboard`

It would be great if the docs could menion that you don't need nuxt fonts, icons, or ui.
With PNPM 10 it worked fine after running `pnpm approve-builds`

But I had to run `pnpm approve-builds` immediately after `pnpm i`. If I ran it after `pnpm run dev` then it didn't work.

**Comment by gabrielstuff** [comment]
> It would be great if the docs could menion that you don't need nuxt fonts, icons, or ui. 

I confirm that selecting nuxt-fonts, nuxt-icons and nuxt-ui lead me to issue running the project from a simple fresh install.
